<?xml version="1.0" encoding="utf-8"?><Database Name="pgbudget" Class="PGDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=pgbudget;Integrated Security=True" SettingsObjectName="pgbudget.Properties.Settings" SettingsPropertyName="pgbudgetConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.project" Member="projects">
    <Type Name="project">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="工程名称" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="工程编号" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="工程地址" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="合同编号" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="图纸编号" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="建设单位" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="编制单位" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="编制人" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="编制日期" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="设计单位" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="设计单位负责人" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="施工单位" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="施工单位负责人" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="审核单位" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="审核单位负责人" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="复核日期" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="招标人" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="投标人" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="投标人备注" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="地形" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="施工地点" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="地区分类" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="运输距离" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="变压器安装方式" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="人工费调整" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="其他费用" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="建筑工程材机费" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="人工运距" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="汽车运距" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="土质" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="备注" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="创建日期" AutoSync="OnUpdate" Type="System.DateTime" DbType="datetime" IsDbGenerated="true" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.desyb" Member="desybs">
    <Type Name="desyb">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="syID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NodeId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BTM" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.deb" Member="debs">
    <Type Name="deb">
      <Column Name="ID" Type="System.Int32" DbType="Int" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="deh" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="zj" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="sybh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mc" Type="System.String" DbType="NVarChar(160)" CanBeNull="true" />
      <Column Name="dw" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="dergf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="declf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dejxf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ylglf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="elglf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="slglf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FACTOR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JBDW" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ZMLB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZYID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FYWJ" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.project_drawing" Member="project_drawings">
    <Type Name="project_drawing">
      <Column Name="project_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="drawing_content" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="drawing_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cjsyb" Member="cjsybs">
    <Type Name="cjsyb">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="syID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NodeId" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BTM" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cjb" Member="cjbs">
    <Type Name="cjb">
      <Column Name="cjid" Type="System.String" DbType="NVarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sybh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="xhgg" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dw" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="dedj" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="scdj" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="nbdj" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="cjlb" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="xs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="cj" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SCBH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCXS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="upsize_ts" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.sbb" Member="sbbs">
    <Type Name="sbb">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SORTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SUBTYPE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MKTPRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BGTPRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ORGPRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WEIGHT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TRAFFICPER" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FACTORY" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sbsyb" Member="sbsybs">
    <Type Name="sbsyb">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LAYER" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.zcb" Member="zcbs">
    <Type Name="zcb">
      <Column Name="Category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SORTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="SPEC1" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="SPEC2" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SUBTYPE" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="MKTPRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BGTPRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ORGPRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WEIGHT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ULLAGE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SECTIONAREA" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LINEWEIGHT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ORGBGTPRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ADJUSTCOE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MAKELENGTH" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.zcsyb" Member="zcsybs">
    <Type Name="zcsyb">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LAYER" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.zjk" Member="zjks">
    <Type Name="zjk">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="created_time" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="zjk_zjk_item" Member="zjk_items" ThisKey="Id" OtherKey="zjk_id" Type="zjk_item" />
    </Type>
  </Table>
  <Table Name="dbo.zjk_item" Member="zjk_items">
    <Type Name="zjk_item">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="zjk_id" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="item_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item_code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="item_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="zjk_zjk_item" Member="zjk" ThisKey="zjk_id" OtherKey="Id" Type="zjk" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.jzgc" Member="jzgcs">
    <Type Name="jzgc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="noid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="gcbh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="mc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="gclb" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dek" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="defile" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zj" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="zb" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dw" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zjf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rgf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="clf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="jxf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="glf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="zcf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sbf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="jcf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="jsf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="jsdw" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="jsdd" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="sgdw" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bzr" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="jksb" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="sbfl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="jksbf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bz" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="rows" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zjbl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bl1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bl2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="hsb" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bg0" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bg10" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bg2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="qtb1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="qtb2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="qtb3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="qtb4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bg6" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bg9" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bg8" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="taset" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bgset" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bgset1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="qtset" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="jfset" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ybset" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bbset" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zjset" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>