#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgbudget
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pgbudget")]
	public partial class PGDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertproject(project instance);
    partial void Updateproject(project instance);
    partial void Deleteproject(project instance);
    partial void Insertdesyb(desyb instance);
    partial void Updatedesyb(desyb instance);
    partial void Deletedesyb(desyb instance);
    partial void Insertdeb(deb instance);
    partial void Updatedeb(deb instance);
    partial void Deletedeb(deb instance);
    partial void Insertproject_drawing(project_drawing instance);
    partial void Updateproject_drawing(project_drawing instance);
    partial void Deleteproject_drawing(project_drawing instance);
    partial void Insertcjsyb(cjsyb instance);
    partial void Updatecjsyb(cjsyb instance);
    partial void Deletecjsyb(cjsyb instance);
    partial void Insertcjb(cjb instance);
    partial void Updatecjb(cjb instance);
    partial void Deletecjb(cjb instance);
    partial void Insertsbb(sbb instance);
    partial void Updatesbb(sbb instance);
    partial void Deletesbb(sbb instance);
    partial void Insertsbsyb(sbsyb instance);
    partial void Updatesbsyb(sbsyb instance);
    partial void Deletesbsyb(sbsyb instance);
    partial void Insertzcb(zcb instance);
    partial void Updatezcb(zcb instance);
    partial void Deletezcb(zcb instance);
    partial void Insertzcsyb(zcsyb instance);
    partial void Updatezcsyb(zcsyb instance);
    partial void Deletezcsyb(zcsyb instance);
    partial void Insertzjk(zjk instance);
    partial void Updatezjk(zjk instance);
    partial void Deletezjk(zjk instance);
    partial void Insertzjk_item(zjk_item instance);
    partial void Updatezjk_item(zjk_item instance);
    partial void Deletezjk_item(zjk_item instance);
    #endregion
		
		public PGDataClassesDataContext() : 
				base(global::pgbudget.Properties.Settings.Default.pgbudgetConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public PGDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PGDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PGDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PGDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<project> projects
		{
			get
			{
				return this.GetTable<project>();
			}
		}
		
		public System.Data.Linq.Table<desyb> desybs
		{
			get
			{
				return this.GetTable<desyb>();
			}
		}
		
		public System.Data.Linq.Table<deb> debs
		{
			get
			{
				return this.GetTable<deb>();
			}
		}
		
		public System.Data.Linq.Table<project_drawing> project_drawings
		{
			get
			{
				return this.GetTable<project_drawing>();
			}
		}
		
		public System.Data.Linq.Table<cjsyb> cjsybs
		{
			get
			{
				return this.GetTable<cjsyb>();
			}
		}
		
		public System.Data.Linq.Table<cjb> cjbs
		{
			get
			{
				return this.GetTable<cjb>();
			}
		}
		
		public System.Data.Linq.Table<sbb> sbbs
		{
			get
			{
				return this.GetTable<sbb>();
			}
		}
		
		public System.Data.Linq.Table<sbsyb> sbsybs
		{
			get
			{
				return this.GetTable<sbsyb>();
			}
		}
		
		public System.Data.Linq.Table<zcb> zcbs
		{
			get
			{
				return this.GetTable<zcb>();
			}
		}
		
		public System.Data.Linq.Table<zcsyb> zcsybs
		{
			get
			{
				return this.GetTable<zcsyb>();
			}
		}
		
		public System.Data.Linq.Table<zjk> zjks
		{
			get
			{
				return this.GetTable<zjk>();
			}
		}
		
		public System.Data.Linq.Table<zjk_item> zjk_items
		{
			get
			{
				return this.GetTable<zjk_item>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.project")]
	public partial class project : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _工程名称;
		
		private string _工程编号;
		
		private string _工程地址;
		
		private string _合同编号;
		
		private string _图纸编号;
		
		private string _建设单位;
		
		private string _编制单位;
		
		private string _编制人;
		
		private System.Nullable<System.DateTime> _编制日期;
		
		private string _设计单位;
		
		private string _设计单位负责人;
		
		private string _施工单位;
		
		private string _施工单位负责人;
		
		private string _审核单位;
		
		private string _审核单位负责人;
		
		private System.Nullable<System.DateTime> _复核日期;
		
		private string _招标人;
		
		private string _投标人;
		
		private string _投标人备注;
		
		private string _地形;
		
		private string _施工地点;
		
		private string _地区分类;
		
		private string _运输距离;
		
		private string _变压器安装方式;
		
		private string _人工费调整;
		
		private System.Nullable<decimal> _其他费用;
		
		private System.Nullable<decimal> _建筑工程材机费;
		
		private System.Nullable<decimal> _人工运距;
		
		private System.Nullable<decimal> _汽车运距;
		
		private string _土质;
		
		private string _备注;
		
		private System.Nullable<System.DateTime> _创建日期;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void On工程名称Changing(string value);
    partial void On工程名称Changed();
    partial void On工程编号Changing(string value);
    partial void On工程编号Changed();
    partial void On工程地址Changing(string value);
    partial void On工程地址Changed();
    partial void On合同编号Changing(string value);
    partial void On合同编号Changed();
    partial void On图纸编号Changing(string value);
    partial void On图纸编号Changed();
    partial void On建设单位Changing(string value);
    partial void On建设单位Changed();
    partial void On编制单位Changing(string value);
    partial void On编制单位Changed();
    partial void On编制人Changing(string value);
    partial void On编制人Changed();
    partial void On编制日期Changing(System.Nullable<System.DateTime> value);
    partial void On编制日期Changed();
    partial void On设计单位Changing(string value);
    partial void On设计单位Changed();
    partial void On设计单位负责人Changing(string value);
    partial void On设计单位负责人Changed();
    partial void On施工单位Changing(string value);
    partial void On施工单位Changed();
    partial void On施工单位负责人Changing(string value);
    partial void On施工单位负责人Changed();
    partial void On审核单位Changing(string value);
    partial void On审核单位Changed();
    partial void On审核单位负责人Changing(string value);
    partial void On审核单位负责人Changed();
    partial void On复核日期Changing(System.Nullable<System.DateTime> value);
    partial void On复核日期Changed();
    partial void On招标人Changing(string value);
    partial void On招标人Changed();
    partial void On投标人Changing(string value);
    partial void On投标人Changed();
    partial void On投标人备注Changing(string value);
    partial void On投标人备注Changed();
    partial void On地形Changing(string value);
    partial void On地形Changed();
    partial void On施工地点Changing(string value);
    partial void On施工地点Changed();
    partial void On地区分类Changing(string value);
    partial void On地区分类Changed();
    partial void On运输距离Changing(string value);
    partial void On运输距离Changed();
    partial void On变压器安装方式Changing(string value);
    partial void On变压器安装方式Changed();
    partial void On人工费调整Changing(string value);
    partial void On人工费调整Changed();
    partial void On其他费用Changing(System.Nullable<decimal> value);
    partial void On其他费用Changed();
    partial void On建筑工程材机费Changing(System.Nullable<decimal> value);
    partial void On建筑工程材机费Changed();
    partial void On人工运距Changing(System.Nullable<decimal> value);
    partial void On人工运距Changed();
    partial void On汽车运距Changing(System.Nullable<decimal> value);
    partial void On汽车运距Changed();
    partial void On土质Changing(string value);
    partial void On土质Changed();
    partial void On备注Changing(string value);
    partial void On备注Changed();
    partial void On创建日期Changing(System.Nullable<System.DateTime> value);
    partial void On创建日期Changed();
    #endregion
		
		public project()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_工程名称", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 工程名称
		{
			get
			{
				return this._工程名称;
			}
			set
			{
				if ((this._工程名称 != value))
				{
					this.On工程名称Changing(value);
					this.SendPropertyChanging();
					this._工程名称 = value;
					this.SendPropertyChanged("工程名称");
					this.On工程名称Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_工程编号", DbType="VarChar(50)")]
		public string 工程编号
		{
			get
			{
				return this._工程编号;
			}
			set
			{
				if ((this._工程编号 != value))
				{
					this.On工程编号Changing(value);
					this.SendPropertyChanging();
					this._工程编号 = value;
					this.SendPropertyChanged("工程编号");
					this.On工程编号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_工程地址", DbType="VarChar(50)")]
		public string 工程地址
		{
			get
			{
				return this._工程地址;
			}
			set
			{
				if ((this._工程地址 != value))
				{
					this.On工程地址Changing(value);
					this.SendPropertyChanging();
					this._工程地址 = value;
					this.SendPropertyChanged("工程地址");
					this.On工程地址Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_合同编号", DbType="VarChar(50)")]
		public string 合同编号
		{
			get
			{
				return this._合同编号;
			}
			set
			{
				if ((this._合同编号 != value))
				{
					this.On合同编号Changing(value);
					this.SendPropertyChanging();
					this._合同编号 = value;
					this.SendPropertyChanged("合同编号");
					this.On合同编号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_图纸编号", DbType="VarChar(50)")]
		public string 图纸编号
		{
			get
			{
				return this._图纸编号;
			}
			set
			{
				if ((this._图纸编号 != value))
				{
					this.On图纸编号Changing(value);
					this.SendPropertyChanging();
					this._图纸编号 = value;
					this.SendPropertyChanged("图纸编号");
					this.On图纸编号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_建设单位", DbType="VarChar(50)")]
		public string 建设单位
		{
			get
			{
				return this._建设单位;
			}
			set
			{
				if ((this._建设单位 != value))
				{
					this.On建设单位Changing(value);
					this.SendPropertyChanging();
					this._建设单位 = value;
					this.SendPropertyChanged("建设单位");
					this.On建设单位Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_编制单位", DbType="VarChar(50)")]
		public string 编制单位
		{
			get
			{
				return this._编制单位;
			}
			set
			{
				if ((this._编制单位 != value))
				{
					this.On编制单位Changing(value);
					this.SendPropertyChanging();
					this._编制单位 = value;
					this.SendPropertyChanged("编制单位");
					this.On编制单位Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_编制人", DbType="VarChar(50)")]
		public string 编制人
		{
			get
			{
				return this._编制人;
			}
			set
			{
				if ((this._编制人 != value))
				{
					this.On编制人Changing(value);
					this.SendPropertyChanging();
					this._编制人 = value;
					this.SendPropertyChanged("编制人");
					this.On编制人Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_编制日期", DbType="DateTime")]
		public System.Nullable<System.DateTime> 编制日期
		{
			get
			{
				return this._编制日期;
			}
			set
			{
				if ((this._编制日期 != value))
				{
					this.On编制日期Changing(value);
					this.SendPropertyChanging();
					this._编制日期 = value;
					this.SendPropertyChanged("编制日期");
					this.On编制日期Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_设计单位", DbType="VarChar(50)")]
		public string 设计单位
		{
			get
			{
				return this._设计单位;
			}
			set
			{
				if ((this._设计单位 != value))
				{
					this.On设计单位Changing(value);
					this.SendPropertyChanging();
					this._设计单位 = value;
					this.SendPropertyChanged("设计单位");
					this.On设计单位Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_设计单位负责人", DbType="VarChar(50)")]
		public string 设计单位负责人
		{
			get
			{
				return this._设计单位负责人;
			}
			set
			{
				if ((this._设计单位负责人 != value))
				{
					this.On设计单位负责人Changing(value);
					this.SendPropertyChanging();
					this._设计单位负责人 = value;
					this.SendPropertyChanged("设计单位负责人");
					this.On设计单位负责人Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_施工单位", DbType="VarChar(50)")]
		public string 施工单位
		{
			get
			{
				return this._施工单位;
			}
			set
			{
				if ((this._施工单位 != value))
				{
					this.On施工单位Changing(value);
					this.SendPropertyChanging();
					this._施工单位 = value;
					this.SendPropertyChanged("施工单位");
					this.On施工单位Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_施工单位负责人", DbType="VarChar(50)")]
		public string 施工单位负责人
		{
			get
			{
				return this._施工单位负责人;
			}
			set
			{
				if ((this._施工单位负责人 != value))
				{
					this.On施工单位负责人Changing(value);
					this.SendPropertyChanging();
					this._施工单位负责人 = value;
					this.SendPropertyChanged("施工单位负责人");
					this.On施工单位负责人Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_审核单位", DbType="VarChar(50)")]
		public string 审核单位
		{
			get
			{
				return this._审核单位;
			}
			set
			{
				if ((this._审核单位 != value))
				{
					this.On审核单位Changing(value);
					this.SendPropertyChanging();
					this._审核单位 = value;
					this.SendPropertyChanged("审核单位");
					this.On审核单位Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_审核单位负责人", DbType="VarChar(50)")]
		public string 审核单位负责人
		{
			get
			{
				return this._审核单位负责人;
			}
			set
			{
				if ((this._审核单位负责人 != value))
				{
					this.On审核单位负责人Changing(value);
					this.SendPropertyChanging();
					this._审核单位负责人 = value;
					this.SendPropertyChanged("审核单位负责人");
					this.On审核单位负责人Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_复核日期", DbType="DateTime")]
		public System.Nullable<System.DateTime> 复核日期
		{
			get
			{
				return this._复核日期;
			}
			set
			{
				if ((this._复核日期 != value))
				{
					this.On复核日期Changing(value);
					this.SendPropertyChanging();
					this._复核日期 = value;
					this.SendPropertyChanged("复核日期");
					this.On复核日期Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_招标人", DbType="VarChar(50)")]
		public string 招标人
		{
			get
			{
				return this._招标人;
			}
			set
			{
				if ((this._招标人 != value))
				{
					this.On招标人Changing(value);
					this.SendPropertyChanging();
					this._招标人 = value;
					this.SendPropertyChanged("招标人");
					this.On招标人Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_投标人", DbType="VarChar(50)")]
		public string 投标人
		{
			get
			{
				return this._投标人;
			}
			set
			{
				if ((this._投标人 != value))
				{
					this.On投标人Changing(value);
					this.SendPropertyChanging();
					this._投标人 = value;
					this.SendPropertyChanged("投标人");
					this.On投标人Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_投标人备注", DbType="VarChar(50)")]
		public string 投标人备注
		{
			get
			{
				return this._投标人备注;
			}
			set
			{
				if ((this._投标人备注 != value))
				{
					this.On投标人备注Changing(value);
					this.SendPropertyChanging();
					this._投标人备注 = value;
					this.SendPropertyChanged("投标人备注");
					this.On投标人备注Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_地形", DbType="VarChar(50)")]
		public string 地形
		{
			get
			{
				return this._地形;
			}
			set
			{
				if ((this._地形 != value))
				{
					this.On地形Changing(value);
					this.SendPropertyChanging();
					this._地形 = value;
					this.SendPropertyChanged("地形");
					this.On地形Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_施工地点", DbType="VarChar(50)")]
		public string 施工地点
		{
			get
			{
				return this._施工地点;
			}
			set
			{
				if ((this._施工地点 != value))
				{
					this.On施工地点Changing(value);
					this.SendPropertyChanging();
					this._施工地点 = value;
					this.SendPropertyChanged("施工地点");
					this.On施工地点Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_地区分类", DbType="VarChar(50)")]
		public string 地区分类
		{
			get
			{
				return this._地区分类;
			}
			set
			{
				if ((this._地区分类 != value))
				{
					this.On地区分类Changing(value);
					this.SendPropertyChanging();
					this._地区分类 = value;
					this.SendPropertyChanged("地区分类");
					this.On地区分类Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_运输距离", DbType="VarChar(50)")]
		public string 运输距离
		{
			get
			{
				return this._运输距离;
			}
			set
			{
				if ((this._运输距离 != value))
				{
					this.On运输距离Changing(value);
					this.SendPropertyChanging();
					this._运输距离 = value;
					this.SendPropertyChanged("运输距离");
					this.On运输距离Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_变压器安装方式", DbType="VarChar(50)")]
		public string 变压器安装方式
		{
			get
			{
				return this._变压器安装方式;
			}
			set
			{
				if ((this._变压器安装方式 != value))
				{
					this.On变压器安装方式Changing(value);
					this.SendPropertyChanging();
					this._变压器安装方式 = value;
					this.SendPropertyChanged("变压器安装方式");
					this.On变压器安装方式Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_人工费调整", DbType="VarChar(50)")]
		public string 人工费调整
		{
			get
			{
				return this._人工费调整;
			}
			set
			{
				if ((this._人工费调整 != value))
				{
					this.On人工费调整Changing(value);
					this.SendPropertyChanging();
					this._人工费调整 = value;
					this.SendPropertyChanged("人工费调整");
					this.On人工费调整Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_其他费用", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> 其他费用
		{
			get
			{
				return this._其他费用;
			}
			set
			{
				if ((this._其他费用 != value))
				{
					this.On其他费用Changing(value);
					this.SendPropertyChanging();
					this._其他费用 = value;
					this.SendPropertyChanged("其他费用");
					this.On其他费用Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_建筑工程材机费", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> 建筑工程材机费
		{
			get
			{
				return this._建筑工程材机费;
			}
			set
			{
				if ((this._建筑工程材机费 != value))
				{
					this.On建筑工程材机费Changing(value);
					this.SendPropertyChanging();
					this._建筑工程材机费 = value;
					this.SendPropertyChanged("建筑工程材机费");
					this.On建筑工程材机费Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_人工运距", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> 人工运距
		{
			get
			{
				return this._人工运距;
			}
			set
			{
				if ((this._人工运距 != value))
				{
					this.On人工运距Changing(value);
					this.SendPropertyChanging();
					this._人工运距 = value;
					this.SendPropertyChanged("人工运距");
					this.On人工运距Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_汽车运距", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> 汽车运距
		{
			get
			{
				return this._汽车运距;
			}
			set
			{
				if ((this._汽车运距 != value))
				{
					this.On汽车运距Changing(value);
					this.SendPropertyChanging();
					this._汽车运距 = value;
					this.SendPropertyChanged("汽车运距");
					this.On汽车运距Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_土质", DbType="VarChar(50)")]
		public string 土质
		{
			get
			{
				return this._土质;
			}
			set
			{
				if ((this._土质 != value))
				{
					this.On土质Changing(value);
					this.SendPropertyChanging();
					this._土质 = value;
					this.SendPropertyChanged("土质");
					this.On土质Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_备注", DbType="VarChar(50)")]
		public string 备注
		{
			get
			{
				return this._备注;
			}
			set
			{
				if ((this._备注 != value))
				{
					this.On备注Changing(value);
					this.SendPropertyChanging();
					this._备注 = value;
					this.SendPropertyChanged("备注");
					this.On备注Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_创建日期", DbType="datetime", IsDbGenerated=true)]
		public System.Nullable<System.DateTime> 创建日期
		{
			get
			{
				return this._创建日期;
			}
			set
			{
				if ((this._创建日期 != value))
				{
					this.On创建日期Changing(value);
					this.SendPropertyChanging();
					this._创建日期 = value;
					this.SendPropertyChanged("创建日期");
					this.On创建日期Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.desyb")]
	public partial class desyb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _syID;
		
		private string _NodeId;
		
		private string _BTM;
		
		private string _NOTE;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsyIDChanging(string value);
    partial void OnsyIDChanged();
    partial void OnNodeIdChanging(string value);
    partial void OnNodeIdChanged();
    partial void OnBTMChanging(string value);
    partial void OnBTMChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    #endregion
		
		public desyb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_syID", DbType="NVarChar(50)")]
		public string syID
		{
			get
			{
				return this._syID;
			}
			set
			{
				if ((this._syID != value))
				{
					this.OnsyIDChanging(value);
					this.SendPropertyChanging();
					this._syID = value;
					this.SendPropertyChanged("syID");
					this.OnsyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeId", DbType="NVarChar(50)")]
		public string NodeId
		{
			get
			{
				return this._NodeId;
			}
			set
			{
				if ((this._NodeId != value))
				{
					this.OnNodeIdChanging(value);
					this.SendPropertyChanging();
					this._NodeId = value;
					this.SendPropertyChanged("NodeId");
					this.OnNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTM", DbType="NVarChar(100)")]
		public string BTM
		{
			get
			{
				return this._BTM;
			}
			set
			{
				if ((this._BTM != value))
				{
					this.OnBTMChanging(value);
					this.SendPropertyChanging();
					this._BTM = value;
					this.SendPropertyChanged("BTM");
					this.OnBTMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.deb")]
	public partial class deb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID;
		
		private string _deh;
		
		private string _zj;
		
		private string _sybh;
		
		private string _mc;
		
		private string _dw;
		
		private System.Nullable<double> _dergf;
		
		private System.Nullable<double> _declf;
		
		private System.Nullable<double> _dejxf;
		
		private System.Nullable<double> _ylglf;
		
		private System.Nullable<double> _elglf;
		
		private System.Nullable<double> _slglf;
		
		private System.Nullable<int> _nrid;
		
		private System.Nullable<int> _FACTOR;
		
		private string _JBDW;
		
		private System.Nullable<int> _ZMLB;
		
		private System.Nullable<int> _ZYID;
		
		private System.Nullable<int> _FYWJ;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OndehChanging(string value);
    partial void OndehChanged();
    partial void OnzjChanging(string value);
    partial void OnzjChanged();
    partial void OnsybhChanging(string value);
    partial void OnsybhChanged();
    partial void OnmcChanging(string value);
    partial void OnmcChanged();
    partial void OndwChanging(string value);
    partial void OndwChanged();
    partial void OndergfChanging(System.Nullable<double> value);
    partial void OndergfChanged();
    partial void OndeclfChanging(System.Nullable<double> value);
    partial void OndeclfChanged();
    partial void OndejxfChanging(System.Nullable<double> value);
    partial void OndejxfChanged();
    partial void OnylglfChanging(System.Nullable<double> value);
    partial void OnylglfChanged();
    partial void OnelglfChanging(System.Nullable<double> value);
    partial void OnelglfChanged();
    partial void OnslglfChanging(System.Nullable<double> value);
    partial void OnslglfChanged();
    partial void OnnridChanging(System.Nullable<int> value);
    partial void OnnridChanged();
    partial void OnFACTORChanging(System.Nullable<int> value);
    partial void OnFACTORChanged();
    partial void OnJBDWChanging(string value);
    partial void OnJBDWChanged();
    partial void OnZMLBChanging(System.Nullable<int> value);
    partial void OnZMLBChanged();
    partial void OnZYIDChanging(System.Nullable<int> value);
    partial void OnZYIDChanged();
    partial void OnFYWJChanging(System.Nullable<int> value);
    partial void OnFYWJChanged();
    #endregion
		
		public deb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int", IsPrimaryKey=true, IsDbGenerated=true)]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deh", DbType="NVarChar(16)")]
		public string deh
		{
			get
			{
				return this._deh;
			}
			set
			{
				if ((this._deh != value))
				{
					this.OndehChanging(value);
					this.SendPropertyChanging();
					this._deh = value;
					this.SendPropertyChanged("deh");
					this.OndehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zj", DbType="NVarChar(10)")]
		public string zj
		{
			get
			{
				return this._zj;
			}
			set
			{
				if ((this._zj != value))
				{
					this.OnzjChanging(value);
					this.SendPropertyChanging();
					this._zj = value;
					this.SendPropertyChanged("zj");
					this.OnzjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sybh", DbType="NVarChar(50)")]
		public string sybh
		{
			get
			{
				return this._sybh;
			}
			set
			{
				if ((this._sybh != value))
				{
					this.OnsybhChanging(value);
					this.SendPropertyChanging();
					this._sybh = value;
					this.SendPropertyChanged("sybh");
					this.OnsybhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mc", DbType="NVarChar(160)")]
		public string mc
		{
			get
			{
				return this._mc;
			}
			set
			{
				if ((this._mc != value))
				{
					this.OnmcChanging(value);
					this.SendPropertyChanging();
					this._mc = value;
					this.SendPropertyChanged("mc");
					this.OnmcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dw", DbType="NVarChar(12)")]
		public string dw
		{
			get
			{
				return this._dw;
			}
			set
			{
				if ((this._dw != value))
				{
					this.OndwChanging(value);
					this.SendPropertyChanging();
					this._dw = value;
					this.SendPropertyChanged("dw");
					this.OndwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dergf", DbType="Float")]
		public System.Nullable<double> dergf
		{
			get
			{
				return this._dergf;
			}
			set
			{
				if ((this._dergf != value))
				{
					this.OndergfChanging(value);
					this.SendPropertyChanging();
					this._dergf = value;
					this.SendPropertyChanged("dergf");
					this.OndergfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_declf", DbType="Float")]
		public System.Nullable<double> declf
		{
			get
			{
				return this._declf;
			}
			set
			{
				if ((this._declf != value))
				{
					this.OndeclfChanging(value);
					this.SendPropertyChanging();
					this._declf = value;
					this.SendPropertyChanged("declf");
					this.OndeclfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dejxf", DbType="Float")]
		public System.Nullable<double> dejxf
		{
			get
			{
				return this._dejxf;
			}
			set
			{
				if ((this._dejxf != value))
				{
					this.OndejxfChanging(value);
					this.SendPropertyChanging();
					this._dejxf = value;
					this.SendPropertyChanged("dejxf");
					this.OndejxfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ylglf", DbType="Float")]
		public System.Nullable<double> ylglf
		{
			get
			{
				return this._ylglf;
			}
			set
			{
				if ((this._ylglf != value))
				{
					this.OnylglfChanging(value);
					this.SendPropertyChanging();
					this._ylglf = value;
					this.SendPropertyChanged("ylglf");
					this.OnylglfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_elglf", DbType="Float")]
		public System.Nullable<double> elglf
		{
			get
			{
				return this._elglf;
			}
			set
			{
				if ((this._elglf != value))
				{
					this.OnelglfChanging(value);
					this.SendPropertyChanging();
					this._elglf = value;
					this.SendPropertyChanged("elglf");
					this.OnelglfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slglf", DbType="Float")]
		public System.Nullable<double> slglf
		{
			get
			{
				return this._slglf;
			}
			set
			{
				if ((this._slglf != value))
				{
					this.OnslglfChanging(value);
					this.SendPropertyChanging();
					this._slglf = value;
					this.SendPropertyChanged("slglf");
					this.OnslglfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrid", DbType="Int")]
		public System.Nullable<int> nrid
		{
			get
			{
				return this._nrid;
			}
			set
			{
				if ((this._nrid != value))
				{
					this.OnnridChanging(value);
					this.SendPropertyChanging();
					this._nrid = value;
					this.SendPropertyChanged("nrid");
					this.OnnridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACTOR", DbType="Int")]
		public System.Nullable<int> FACTOR
		{
			get
			{
				return this._FACTOR;
			}
			set
			{
				if ((this._FACTOR != value))
				{
					this.OnFACTORChanging(value);
					this.SendPropertyChanging();
					this._FACTOR = value;
					this.SendPropertyChanged("FACTOR");
					this.OnFACTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JBDW", DbType="NVarChar(50)")]
		public string JBDW
		{
			get
			{
				return this._JBDW;
			}
			set
			{
				if ((this._JBDW != value))
				{
					this.OnJBDWChanging(value);
					this.SendPropertyChanging();
					this._JBDW = value;
					this.SendPropertyChanged("JBDW");
					this.OnJBDWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZMLB", DbType="Int")]
		public System.Nullable<int> ZMLB
		{
			get
			{
				return this._ZMLB;
			}
			set
			{
				if ((this._ZMLB != value))
				{
					this.OnZMLBChanging(value);
					this.SendPropertyChanging();
					this._ZMLB = value;
					this.SendPropertyChanged("ZMLB");
					this.OnZMLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZYID", DbType="Int")]
		public System.Nullable<int> ZYID
		{
			get
			{
				return this._ZYID;
			}
			set
			{
				if ((this._ZYID != value))
				{
					this.OnZYIDChanging(value);
					this.SendPropertyChanging();
					this._ZYID = value;
					this.SendPropertyChanged("ZYID");
					this.OnZYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FYWJ", DbType="Int")]
		public System.Nullable<int> FYWJ
		{
			get
			{
				return this._FYWJ;
			}
			set
			{
				if ((this._FYWJ != value))
				{
					this.OnFYWJChanging(value);
					this.SendPropertyChanging();
					this._FYWJ = value;
					this.SendPropertyChanged("FYWJ");
					this.OnFYWJChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.project_drawing")]
	public partial class project_drawing : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _project_id;
		
		private System.Xml.Linq.XElement _drawing_content;
		
		private System.Nullable<System.DateTime> _drawing_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproject_idChanging(int value);
    partial void Onproject_idChanged();
    partial void Ondrawing_contentChanging(System.Xml.Linq.XElement value);
    partial void Ondrawing_contentChanged();
    partial void Ondrawing_timeChanging(System.Nullable<System.DateTime> value);
    partial void Ondrawing_timeChanged();
    #endregion
		
		public project_drawing()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_project_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int project_id
		{
			get
			{
				return this._project_id;
			}
			set
			{
				if ((this._project_id != value))
				{
					this.Onproject_idChanging(value);
					this.SendPropertyChanging();
					this._project_id = value;
					this.SendPropertyChanged("project_id");
					this.Onproject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drawing_content", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement drawing_content
		{
			get
			{
				return this._drawing_content;
			}
			set
			{
				if ((this._drawing_content != value))
				{
					this.Ondrawing_contentChanging(value);
					this.SendPropertyChanging();
					this._drawing_content = value;
					this.SendPropertyChanged("drawing_content");
					this.Ondrawing_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drawing_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> drawing_time
		{
			get
			{
				return this._drawing_time;
			}
			set
			{
				if ((this._drawing_time != value))
				{
					this.Ondrawing_timeChanging(value);
					this.SendPropertyChanging();
					this._drawing_time = value;
					this.SendPropertyChanged("drawing_time");
					this.Ondrawing_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cjsyb")]
	public partial class cjsyb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _syID;
		
		private string _NodeId;
		
		private string _BTM;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsyIDChanging(string value);
    partial void OnsyIDChanged();
    partial void OnNodeIdChanging(string value);
    partial void OnNodeIdChanged();
    partial void OnBTMChanging(string value);
    partial void OnBTMChanged();
    #endregion
		
		public cjsyb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_syID", DbType="NVarChar(50)")]
		public string syID
		{
			get
			{
				return this._syID;
			}
			set
			{
				if ((this._syID != value))
				{
					this.OnsyIDChanging(value);
					this.SendPropertyChanging();
					this._syID = value;
					this.SendPropertyChanged("syID");
					this.OnsyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeId", DbType="NVarChar(20)")]
		public string NodeId
		{
			get
			{
				return this._NodeId;
			}
			set
			{
				if ((this._NodeId != value))
				{
					this.OnNodeIdChanging(value);
					this.SendPropertyChanging();
					this._NodeId = value;
					this.SendPropertyChanged("NodeId");
					this.OnNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTM", DbType="NVarChar(100)")]
		public string BTM
		{
			get
			{
				return this._BTM;
			}
			set
			{
				if ((this._BTM != value))
				{
					this.OnBTMChanging(value);
					this.SendPropertyChanging();
					this._BTM = value;
					this.SendPropertyChanged("BTM");
					this.OnBTMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cjb")]
	public partial class cjb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cjid;
		
		private string _sybh;
		
		private string _mc;
		
		private string _xhgg;
		
		private string _dw;
		
		private string _dedj;
		
		private string _scdj;
		
		private string _nbdj;
		
		private System.Nullable<int> _cjlb;
		
		private System.Nullable<double> _xs;
		
		private bool _sc;
		
		private string _cj;
		
		private System.Nullable<int> _SCBH;
		
		private System.Nullable<double> _SCXS;
		
		private System.Data.Linq.Binary _upsize_ts;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncjidChanging(string value);
    partial void OncjidChanged();
    partial void OnsybhChanging(string value);
    partial void OnsybhChanged();
    partial void OnmcChanging(string value);
    partial void OnmcChanged();
    partial void OnxhggChanging(string value);
    partial void OnxhggChanged();
    partial void OndwChanging(string value);
    partial void OndwChanged();
    partial void OndedjChanging(string value);
    partial void OndedjChanged();
    partial void OnscdjChanging(string value);
    partial void OnscdjChanged();
    partial void OnnbdjChanging(string value);
    partial void OnnbdjChanged();
    partial void OncjlbChanging(System.Nullable<int> value);
    partial void OncjlbChanged();
    partial void OnxsChanging(System.Nullable<double> value);
    partial void OnxsChanged();
    partial void OnscChanging(bool value);
    partial void OnscChanged();
    partial void OncjChanging(string value);
    partial void OncjChanged();
    partial void OnSCBHChanging(System.Nullable<int> value);
    partial void OnSCBHChanged();
    partial void OnSCXSChanging(System.Nullable<double> value);
    partial void OnSCXSChanged();
    partial void Onupsize_tsChanging(System.Data.Linq.Binary value);
    partial void Onupsize_tsChanged();
    #endregion
		
		public cjb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cjid", DbType="NVarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string cjid
		{
			get
			{
				return this._cjid;
			}
			set
			{
				if ((this._cjid != value))
				{
					this.OncjidChanging(value);
					this.SendPropertyChanging();
					this._cjid = value;
					this.SendPropertyChanged("cjid");
					this.OncjidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sybh", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string sybh
		{
			get
			{
				return this._sybh;
			}
			set
			{
				if ((this._sybh != value))
				{
					this.OnsybhChanging(value);
					this.SendPropertyChanging();
					this._sybh = value;
					this.SendPropertyChanged("sybh");
					this.OnsybhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mc", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string mc
		{
			get
			{
				return this._mc;
			}
			set
			{
				if ((this._mc != value))
				{
					this.OnmcChanging(value);
					this.SendPropertyChanging();
					this._mc = value;
					this.SendPropertyChanged("mc");
					this.OnmcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xhgg", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string xhgg
		{
			get
			{
				return this._xhgg;
			}
			set
			{
				if ((this._xhgg != value))
				{
					this.OnxhggChanging(value);
					this.SendPropertyChanging();
					this._xhgg = value;
					this.SendPropertyChanged("xhgg");
					this.OnxhggChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dw", DbType="NVarChar(12)", UpdateCheck=UpdateCheck.Never)]
		public string dw
		{
			get
			{
				return this._dw;
			}
			set
			{
				if ((this._dw != value))
				{
					this.OndwChanging(value);
					this.SendPropertyChanging();
					this._dw = value;
					this.SendPropertyChanged("dw");
					this.OndwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dedj", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string dedj
		{
			get
			{
				return this._dedj;
			}
			set
			{
				if ((this._dedj != value))
				{
					this.OndedjChanging(value);
					this.SendPropertyChanging();
					this._dedj = value;
					this.SendPropertyChanged("dedj");
					this.OndedjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scdj", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string scdj
		{
			get
			{
				return this._scdj;
			}
			set
			{
				if ((this._scdj != value))
				{
					this.OnscdjChanging(value);
					this.SendPropertyChanging();
					this._scdj = value;
					this.SendPropertyChanged("scdj");
					this.OnscdjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbdj", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string nbdj
		{
			get
			{
				return this._nbdj;
			}
			set
			{
				if ((this._nbdj != value))
				{
					this.OnnbdjChanging(value);
					this.SendPropertyChanging();
					this._nbdj = value;
					this.SendPropertyChanged("nbdj");
					this.OnnbdjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cjlb", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> cjlb
		{
			get
			{
				return this._cjlb;
			}
			set
			{
				if ((this._cjlb != value))
				{
					this.OncjlbChanging(value);
					this.SendPropertyChanging();
					this._cjlb = value;
					this.SendPropertyChanged("cjlb");
					this.OncjlbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xs", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> xs
		{
			get
			{
				return this._xs;
			}
			set
			{
				if ((this._xs != value))
				{
					this.OnxsChanging(value);
					this.SendPropertyChanging();
					this._xs = value;
					this.SendPropertyChanged("xs");
					this.OnxsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sc", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool sc
		{
			get
			{
				return this._sc;
			}
			set
			{
				if ((this._sc != value))
				{
					this.OnscChanging(value);
					this.SendPropertyChanging();
					this._sc = value;
					this.SendPropertyChanged("sc");
					this.OnscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cj", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string cj
		{
			get
			{
				return this._cj;
			}
			set
			{
				if ((this._cj != value))
				{
					this.OncjChanging(value);
					this.SendPropertyChanging();
					this._cj = value;
					this.SendPropertyChanged("cj");
					this.OncjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCBH", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> SCBH
		{
			get
			{
				return this._SCBH;
			}
			set
			{
				if ((this._SCBH != value))
				{
					this.OnSCBHChanging(value);
					this.SendPropertyChanging();
					this._SCBH = value;
					this.SendPropertyChanged("SCBH");
					this.OnSCBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCXS", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> SCXS
		{
			get
			{
				return this._SCXS;
			}
			set
			{
				if ((this._SCXS != value))
				{
					this.OnSCXSChanging(value);
					this.SendPropertyChanging();
					this._SCXS = value;
					this.SendPropertyChanged("SCXS");
					this.OnSCXSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upsize_ts", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary upsize_ts
		{
			get
			{
				return this._upsize_ts;
			}
			set
			{
				if ((this._upsize_ts != value))
				{
					this.Onupsize_tsChanging(value);
					this.SendPropertyChanging();
					this._upsize_ts = value;
					this.SendPropertyChanged("upsize_ts");
					this.Onupsize_tsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sbb")]
	public partial class sbb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Category;
		
		private string _CODE;
		
		private System.Nullable<int> _SORTID;
		
		private string _NAME;
		
		private string _UNIT;
		
		private string _TYPE;
		
		private string _SUBTYPE;
		
		private System.Nullable<double> _MKTPRICE;
		
		private System.Nullable<double> _BGTPRICE;
		
		private System.Nullable<double> _ORGPRICE;
		
		private System.Nullable<double> _WEIGHT;
		
		private System.Nullable<double> _TRAFFICPER;
		
		private string _FACTORY;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCategoryChanging(System.Nullable<int> value);
    partial void OnCategoryChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnSORTIDChanging(System.Nullable<int> value);
    partial void OnSORTIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnUNITChanging(string value);
    partial void OnUNITChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnSUBTYPEChanging(string value);
    partial void OnSUBTYPEChanged();
    partial void OnMKTPRICEChanging(System.Nullable<double> value);
    partial void OnMKTPRICEChanged();
    partial void OnBGTPRICEChanging(System.Nullable<double> value);
    partial void OnBGTPRICEChanged();
    partial void OnORGPRICEChanging(System.Nullable<double> value);
    partial void OnORGPRICEChanged();
    partial void OnWEIGHTChanging(System.Nullable<double> value);
    partial void OnWEIGHTChanged();
    partial void OnTRAFFICPERChanging(System.Nullable<double> value);
    partial void OnTRAFFICPERChanged();
    partial void OnFACTORYChanging(string value);
    partial void OnFACTORYChanged();
    #endregion
		
		public sbb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="Int")]
		public System.Nullable<int> Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(10)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORTID", DbType="Int")]
		public System.Nullable<int> SORTID
		{
			get
			{
				return this._SORTID;
			}
			set
			{
				if ((this._SORTID != value))
				{
					this.OnSORTIDChanging(value);
					this.SendPropertyChanging();
					this._SORTID = value;
					this.SendPropertyChanged("SORTID");
					this.OnSORTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(60)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT", DbType="NVarChar(10)")]
		public string UNIT
		{
			get
			{
				return this._UNIT;
			}
			set
			{
				if ((this._UNIT != value))
				{
					this.OnUNITChanging(value);
					this.SendPropertyChanging();
					this._UNIT = value;
					this.SendPropertyChanged("UNIT");
					this.OnUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(10)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTYPE", DbType="NVarChar(10)")]
		public string SUBTYPE
		{
			get
			{
				return this._SUBTYPE;
			}
			set
			{
				if ((this._SUBTYPE != value))
				{
					this.OnSUBTYPEChanging(value);
					this.SendPropertyChanging();
					this._SUBTYPE = value;
					this.SendPropertyChanged("SUBTYPE");
					this.OnSUBTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MKTPRICE", DbType="Float")]
		public System.Nullable<double> MKTPRICE
		{
			get
			{
				return this._MKTPRICE;
			}
			set
			{
				if ((this._MKTPRICE != value))
				{
					this.OnMKTPRICEChanging(value);
					this.SendPropertyChanging();
					this._MKTPRICE = value;
					this.SendPropertyChanged("MKTPRICE");
					this.OnMKTPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGTPRICE", DbType="Float")]
		public System.Nullable<double> BGTPRICE
		{
			get
			{
				return this._BGTPRICE;
			}
			set
			{
				if ((this._BGTPRICE != value))
				{
					this.OnBGTPRICEChanging(value);
					this.SendPropertyChanging();
					this._BGTPRICE = value;
					this.SendPropertyChanged("BGTPRICE");
					this.OnBGTPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORGPRICE", DbType="Float")]
		public System.Nullable<double> ORGPRICE
		{
			get
			{
				return this._ORGPRICE;
			}
			set
			{
				if ((this._ORGPRICE != value))
				{
					this.OnORGPRICEChanging(value);
					this.SendPropertyChanging();
					this._ORGPRICE = value;
					this.SendPropertyChanged("ORGPRICE");
					this.OnORGPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHT", DbType="Float")]
		public System.Nullable<double> WEIGHT
		{
			get
			{
				return this._WEIGHT;
			}
			set
			{
				if ((this._WEIGHT != value))
				{
					this.OnWEIGHTChanging(value);
					this.SendPropertyChanging();
					this._WEIGHT = value;
					this.SendPropertyChanged("WEIGHT");
					this.OnWEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAFFICPER", DbType="Float")]
		public System.Nullable<double> TRAFFICPER
		{
			get
			{
				return this._TRAFFICPER;
			}
			set
			{
				if ((this._TRAFFICPER != value))
				{
					this.OnTRAFFICPERChanging(value);
					this.SendPropertyChanging();
					this._TRAFFICPER = value;
					this.SendPropertyChanged("TRAFFICPER");
					this.OnTRAFFICPERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACTORY", DbType="NVarChar(10)")]
		public string FACTORY
		{
			get
			{
				return this._FACTORY;
			}
			set
			{
				if ((this._FACTORY != value))
				{
					this.OnFACTORYChanging(value);
					this.SendPropertyChanging();
					this._FACTORY = value;
					this.SendPropertyChanged("FACTORY");
					this.OnFACTORYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sbsyb")]
	public partial class sbsyb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LAYER;
		
		private string _CODE;
		
		private string _NAME;
		
		private string _REMARK;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLAYERChanging(string value);
    partial void OnLAYERChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    #endregion
		
		public sbsyb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAYER", DbType="NVarChar(10)")]
		public string LAYER
		{
			get
			{
				return this._LAYER;
			}
			set
			{
				if ((this._LAYER != value))
				{
					this.OnLAYERChanging(value);
					this.SendPropertyChanging();
					this._LAYER = value;
					this.SendPropertyChanged("LAYER");
					this.OnLAYERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(10)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(40)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="NVarChar(10)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zcb")]
	public partial class zcb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _Category;
		
		private int _ID;
		
		private string _CODE;
		
		private System.Nullable<int> _SORTID;
		
		private string _NAME;
		
		private string _SPEC1;
		
		private string _SPEC2;
		
		private string _UNIT;
		
		private string _TYPE;
		
		private string _SUBTYPE;
		
		private System.Nullable<double> _MKTPRICE;
		
		private System.Nullable<double> _BGTPRICE;
		
		private System.Nullable<double> _ORGPRICE;
		
		private System.Nullable<double> _WEIGHT;
		
		private System.Nullable<double> _ULLAGE;
		
		private string _SECTIONAREA;
		
		private System.Nullable<double> _LINEWEIGHT;
		
		private System.Nullable<double> _ORGBGTPRICE;
		
		private System.Nullable<double> _ADJUSTCOE;
		
		private System.Nullable<double> _MAKELENGTH;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryChanging(System.Nullable<int> value);
    partial void OnCategoryChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnSORTIDChanging(System.Nullable<int> value);
    partial void OnSORTIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnSPEC1Changing(string value);
    partial void OnSPEC1Changed();
    partial void OnSPEC2Changing(string value);
    partial void OnSPEC2Changed();
    partial void OnUNITChanging(string value);
    partial void OnUNITChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnSUBTYPEChanging(string value);
    partial void OnSUBTYPEChanged();
    partial void OnMKTPRICEChanging(System.Nullable<double> value);
    partial void OnMKTPRICEChanged();
    partial void OnBGTPRICEChanging(System.Nullable<double> value);
    partial void OnBGTPRICEChanged();
    partial void OnORGPRICEChanging(System.Nullable<double> value);
    partial void OnORGPRICEChanged();
    partial void OnWEIGHTChanging(System.Nullable<double> value);
    partial void OnWEIGHTChanged();
    partial void OnULLAGEChanging(System.Nullable<double> value);
    partial void OnULLAGEChanged();
    partial void OnSECTIONAREAChanging(string value);
    partial void OnSECTIONAREAChanged();
    partial void OnLINEWEIGHTChanging(System.Nullable<double> value);
    partial void OnLINEWEIGHTChanged();
    partial void OnORGBGTPRICEChanging(System.Nullable<double> value);
    partial void OnORGBGTPRICEChanged();
    partial void OnADJUSTCOEChanging(System.Nullable<double> value);
    partial void OnADJUSTCOEChanged();
    partial void OnMAKELENGTHChanging(System.Nullable<double> value);
    partial void OnMAKELENGTHChanged();
    #endregion
		
		public zcb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="Int")]
		public System.Nullable<int> Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(10)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORTID", DbType="Int")]
		public System.Nullable<int> SORTID
		{
			get
			{
				return this._SORTID;
			}
			set
			{
				if ((this._SORTID != value))
				{
					this.OnSORTIDChanging(value);
					this.SendPropertyChanging();
					this._SORTID = value;
					this.SendPropertyChanged("SORTID");
					this.OnSORTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(40)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPEC1", DbType="NVarChar(40)")]
		public string SPEC1
		{
			get
			{
				return this._SPEC1;
			}
			set
			{
				if ((this._SPEC1 != value))
				{
					this.OnSPEC1Changing(value);
					this.SendPropertyChanging();
					this._SPEC1 = value;
					this.SendPropertyChanged("SPEC1");
					this.OnSPEC1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPEC2", DbType="NVarChar(10)")]
		public string SPEC2
		{
			get
			{
				return this._SPEC2;
			}
			set
			{
				if ((this._SPEC2 != value))
				{
					this.OnSPEC2Changing(value);
					this.SendPropertyChanging();
					this._SPEC2 = value;
					this.SendPropertyChanged("SPEC2");
					this.OnSPEC2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT", DbType="NVarChar(10)")]
		public string UNIT
		{
			get
			{
				return this._UNIT;
			}
			set
			{
				if ((this._UNIT != value))
				{
					this.OnUNITChanging(value);
					this.SendPropertyChanging();
					this._UNIT = value;
					this.SendPropertyChanged("UNIT");
					this.OnUNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(10)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTYPE", DbType="NVarChar(40)")]
		public string SUBTYPE
		{
			get
			{
				return this._SUBTYPE;
			}
			set
			{
				if ((this._SUBTYPE != value))
				{
					this.OnSUBTYPEChanging(value);
					this.SendPropertyChanging();
					this._SUBTYPE = value;
					this.SendPropertyChanged("SUBTYPE");
					this.OnSUBTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MKTPRICE", DbType="Float")]
		public System.Nullable<double> MKTPRICE
		{
			get
			{
				return this._MKTPRICE;
			}
			set
			{
				if ((this._MKTPRICE != value))
				{
					this.OnMKTPRICEChanging(value);
					this.SendPropertyChanging();
					this._MKTPRICE = value;
					this.SendPropertyChanged("MKTPRICE");
					this.OnMKTPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGTPRICE", DbType="Float")]
		public System.Nullable<double> BGTPRICE
		{
			get
			{
				return this._BGTPRICE;
			}
			set
			{
				if ((this._BGTPRICE != value))
				{
					this.OnBGTPRICEChanging(value);
					this.SendPropertyChanging();
					this._BGTPRICE = value;
					this.SendPropertyChanged("BGTPRICE");
					this.OnBGTPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORGPRICE", DbType="Float")]
		public System.Nullable<double> ORGPRICE
		{
			get
			{
				return this._ORGPRICE;
			}
			set
			{
				if ((this._ORGPRICE != value))
				{
					this.OnORGPRICEChanging(value);
					this.SendPropertyChanging();
					this._ORGPRICE = value;
					this.SendPropertyChanged("ORGPRICE");
					this.OnORGPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHT", DbType="Float")]
		public System.Nullable<double> WEIGHT
		{
			get
			{
				return this._WEIGHT;
			}
			set
			{
				if ((this._WEIGHT != value))
				{
					this.OnWEIGHTChanging(value);
					this.SendPropertyChanging();
					this._WEIGHT = value;
					this.SendPropertyChanged("WEIGHT");
					this.OnWEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULLAGE", DbType="Float")]
		public System.Nullable<double> ULLAGE
		{
			get
			{
				return this._ULLAGE;
			}
			set
			{
				if ((this._ULLAGE != value))
				{
					this.OnULLAGEChanging(value);
					this.SendPropertyChanging();
					this._ULLAGE = value;
					this.SendPropertyChanged("ULLAGE");
					this.OnULLAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTIONAREA", DbType="NVarChar(10)")]
		public string SECTIONAREA
		{
			get
			{
				return this._SECTIONAREA;
			}
			set
			{
				if ((this._SECTIONAREA != value))
				{
					this.OnSECTIONAREAChanging(value);
					this.SendPropertyChanging();
					this._SECTIONAREA = value;
					this.SendPropertyChanged("SECTIONAREA");
					this.OnSECTIONAREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINEWEIGHT", DbType="Float")]
		public System.Nullable<double> LINEWEIGHT
		{
			get
			{
				return this._LINEWEIGHT;
			}
			set
			{
				if ((this._LINEWEIGHT != value))
				{
					this.OnLINEWEIGHTChanging(value);
					this.SendPropertyChanging();
					this._LINEWEIGHT = value;
					this.SendPropertyChanged("LINEWEIGHT");
					this.OnLINEWEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORGBGTPRICE", DbType="Float")]
		public System.Nullable<double> ORGBGTPRICE
		{
			get
			{
				return this._ORGBGTPRICE;
			}
			set
			{
				if ((this._ORGBGTPRICE != value))
				{
					this.OnORGBGTPRICEChanging(value);
					this.SendPropertyChanging();
					this._ORGBGTPRICE = value;
					this.SendPropertyChanged("ORGBGTPRICE");
					this.OnORGBGTPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADJUSTCOE", DbType="Float")]
		public System.Nullable<double> ADJUSTCOE
		{
			get
			{
				return this._ADJUSTCOE;
			}
			set
			{
				if ((this._ADJUSTCOE != value))
				{
					this.OnADJUSTCOEChanging(value);
					this.SendPropertyChanging();
					this._ADJUSTCOE = value;
					this.SendPropertyChanged("ADJUSTCOE");
					this.OnADJUSTCOEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKELENGTH", DbType="Float")]
		public System.Nullable<double> MAKELENGTH
		{
			get
			{
				return this._MAKELENGTH;
			}
			set
			{
				if ((this._MAKELENGTH != value))
				{
					this.OnMAKELENGTHChanging(value);
					this.SendPropertyChanging();
					this._MAKELENGTH = value;
					this.SendPropertyChanged("MAKELENGTH");
					this.OnMAKELENGTHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zcsyb")]
	public partial class zcsyb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LAYER;
		
		private string _CODE;
		
		private string _NAME;
		
		private string _REMARK;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLAYERChanging(string value);
    partial void OnLAYERChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    #endregion
		
		public zcsyb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAYER", DbType="NVarChar(10)")]
		public string LAYER
		{
			get
			{
				return this._LAYER;
			}
			set
			{
				if ((this._LAYER != value))
				{
					this.OnLAYERChanging(value);
					this.SendPropertyChanging();
					this._LAYER = value;
					this.SendPropertyChanged("LAYER");
					this.OnLAYERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(10)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="NVarChar(10)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zjk")]
	public partial class zjk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private string _type;
		
		private System.DateTime _created_time;
		
		private EntitySet<zjk_item> _zjk_items;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Oncreated_timeChanging(System.DateTime value);
    partial void Oncreated_timeChanged();
    #endregion
		
		public zjk()
		{
			this._zjk_items = new EntitySet<zjk_item>(new Action<zjk_item>(this.attach_zjk_items), new Action<zjk_item>(this.detach_zjk_items));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime NOT NULL", IsDbGenerated=true)]
		public System.DateTime created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="zjk_zjk_item", Storage="_zjk_items", ThisKey="Id", OtherKey="zjk_id")]
		public EntitySet<zjk_item> zjk_items
		{
			get
			{
				return this._zjk_items;
			}
			set
			{
				this._zjk_items.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_zjk_items(zjk_item entity)
		{
			this.SendPropertyChanging();
			entity.zjk = this;
		}
		
		private void detach_zjk_items(zjk_item entity)
		{
			this.SendPropertyChanging();
			entity.zjk = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zjk_item")]
	public partial class zjk_item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _zjk_id;
		
		private int _item_type;
		
		private string _item_code;
		
		private string _item_name;
		
		private EntityRef<zjk> _zjk;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onzjk_idChanging(int value);
    partial void Onzjk_idChanged();
    partial void Onitem_typeChanging(int value);
    partial void Onitem_typeChanged();
    partial void Onitem_codeChanging(string value);
    partial void Onitem_codeChanged();
    partial void Onitem_nameChanging(string value);
    partial void Onitem_nameChanged();
    #endregion
		
		public zjk_item()
		{
			this._zjk = default(EntityRef<zjk>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zjk_id", DbType="Int")]
		public int zjk_id
		{
			get
			{
				return this._zjk_id;
			}
			set
			{
				if ((this._zjk_id != value))
				{
					if (this._zjk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onzjk_idChanging(value);
					this.SendPropertyChanging();
					this._zjk_id = value;
					this.SendPropertyChanged("zjk_id");
					this.Onzjk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_type", DbType="Int NOT NULL")]
		public int item_type
		{
			get
			{
				return this._item_type;
			}
			set
			{
				if ((this._item_type != value))
				{
					this.Onitem_typeChanging(value);
					this.SendPropertyChanging();
					this._item_type = value;
					this.SendPropertyChanged("item_type");
					this.Onitem_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string item_code
		{
			get
			{
				return this._item_code;
			}
			set
			{
				if ((this._item_code != value))
				{
					this.Onitem_codeChanging(value);
					this.SendPropertyChanging();
					this._item_code = value;
					this.SendPropertyChanged("item_code");
					this.Onitem_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_name", DbType="VarChar(100)")]
		public string item_name
		{
			get
			{
				return this._item_name;
			}
			set
			{
				if ((this._item_name != value))
				{
					this.Onitem_nameChanging(value);
					this.SendPropertyChanging();
					this._item_name = value;
					this.SendPropertyChanged("item_name");
					this.Onitem_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="zjk_zjk_item", Storage="_zjk", ThisKey="zjk_id", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE", DeleteOnNull=true)]
		public zjk zjk
		{
			get
			{
				return this._zjk.Entity;
			}
			set
			{
				zjk previousValue = this._zjk.Entity;
				if (((previousValue != value) 
							|| (this._zjk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._zjk.Entity = null;
						previousValue.zjk_items.Remove(this);
					}
					this._zjk.Entity = value;
					if ((value != null))
					{
						value.zjk_items.Add(this);
						this._zjk_id = value.Id;
					}
					else
					{
						this._zjk_id = default(int);
					}
					this.SendPropertyChanged("zjk");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
